<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Services/CentralPms/src/ExitPass.CentralPms.Application/ExitPass.CentralPms.Application.csproj" />
    <ProjectReference Include="../../../src/Services/CentralPms/src/ExitPass.CentralPms.Infrastructure/ExitPass.CentralPms.Infrastructure.csproj" />
  </ItemGroup>
</Project>
