namespace ExitPass.CentralPms.Domain.FiscalIssuance;

public enum FiscalIssuanceExceptionReason
{
    MissingPayableBasis = 1,
    MissingUpstreamFinalityReference = 2,
    UnapprovedDiscountReference = 3,
    UnsupportedFiscalDocumentRequest = 4,
    InvalidFiscalTender = 5,
    MissingFiscalTender = 6,
    InvalidFiscalTaxDetail = 7,
    InvalidFiscalDiscountPrivilegeDetail = 8,
    InvalidFiscalTotal = 9,
    SensitivePayloadRejected = 10,
    RequestConstructionError = 11,
    FiscalIdentityNotFound = 20,
    FiscalIdentityAmbiguous = 21,
    FiscalIdentityNotEffective = 22,
    FiscalSequencePolicyNotFound = 23,
    FiscalSequencePolicyAmbiguous = 24,
    FiscalSequencePolicyNotEffective = 25,
    FiscalSequenceStateNotFound = 26,
    FiscalSequenceStateNotEffective = 27,
    FiscalNumberAllocationFailed = 28,
    FiscalDocumentNumberFormatFailed = 29,
    FiscalDocumentIdempotencyConflict = 40,
    ReplayMismatch = 41,
    DuplicateReferenceDetected = 42,
    PersistenceNotConfigured = 60,
    InvalidPersistenceConfiguration = 61,
    PersistenceWriteFailed = 62,
    FiscalNumberAssignmentIncomplete = 63,
    PostTimeout = 64,
    NetworkDisconnectAfterPossibleCommit = 65,
    GetReadbackNotFound = 66,
    GetReadbackServiceFailed = 67,
    GetReadbackInconclusive = 68,
    CentralPmsReferencePersistenceFailed = 69,
    ManualReviewRequired = 80,
    ManualReleaseRequestedAfterFiscalFailure = 81,
    FiscalReferenceMismatch = 82,
    ReconciliationRequired = 83,
    ReconciliationClosed = 84
}
