upstream central_pms_upstream_secure { server central-pms:8443; keepalive 32; }
upstream payment_orchestrator_upstream_secure { server payment-orchestrator:8443; keepalive 32; }
upstream gate_integration_service_upstream_secure { server gate-integration-service:8443; keepalive 32; }

server {
    listen 443 ssl;
    server_name localhost;
    ssl_certificate     /etc/exitpass/certs/server/fullchain.crt;
    ssl_certificate_key /etc/exitpass/certs/server/tls.key;

    client_max_body_size 10m;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Request-Id $request_id;
    proxy_set_header Connection "";

    location = /health/live  { access_log off; default_type text/plain; return 200 'nginx-live'; }
    location = /health/ready { access_log off; default_type text/plain; return 200 'nginx-ready'; }

    location /api/core/ {
        proxy_pass https://central_pms_upstream_secure/;
        proxy_ssl_certificate         /etc/exitpass/certs/client/client.crt;
        proxy_ssl_certificate_key     /etc/exitpass/certs/client/client.key;
        proxy_ssl_trusted_certificate /etc/exitpass/certs/trust/internal-trust-bundle.crt;
        proxy_ssl_verify on;
        proxy_ssl_server_name on;
    }

    location /api/payments/ {
        proxy_pass https://payment_orchestrator_upstream_secure/;
        proxy_ssl_certificate         /etc/exitpass/certs/client/client.crt;
        proxy_ssl_certificate_key     /etc/exitpass/certs/client/client.key;
        proxy_ssl_trusted_certificate /etc/exitpass/certs/trust/internal-trust-bundle.crt;
        proxy_ssl_verify on;
        proxy_ssl_server_name on;
    }
}

server {
    listen 8444 ssl;
    server_name device.local;
    ssl_certificate     /etc/exitpass/certs/server/fullchain.crt;
    ssl_certificate_key /etc/exitpass/certs/server/tls.key;
    ssl_client_certificate /etc/exitpass/certs/trust/internal-trust-bundle.crt;
    ssl_verify_client on;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Request-Id $request_id;
    proxy_set_header Connection "";

    location /api/device/ {
        proxy_pass https://gate_integration_service_upstream_secure/;
        proxy_ssl_certificate         /etc/exitpass/certs/client/client.crt;
        proxy_ssl_certificate_key     /etc/exitpass/certs/client/client.key;
        proxy_ssl_trusted_certificate /etc/exitpass/certs/trust/internal-trust-bundle.crt;
        proxy_ssl_verify on;
        proxy_ssl_server_name on;
    }
}
