namespace ExitPass.CentralPms.Contracts.ManagementPlatform;

public sealed record ManagementPlatformStatutoryEvidenceGovernanceResponse(
    string ContractVersion,
    string? RequestedScopeType,
    Guid? RequestedScopeReference,
    Guid CorrelationId,
    DateTimeOffset EvaluationTimestamp,
    string FreshnessStatus,
    bool Stale,
    IReadOnlyList<ManagementPlatformStatutoryEvidenceGovernanceSiteDto> Sites,
    IReadOnlyList<string> Warnings,
    IReadOnlyList<string> Blockers);

public sealed record ManagementPlatformStatutoryEvidenceGovernanceSiteDto(
    Guid SiteReference,
    string? SiteDisplayName,
    Guid SiteGroupReference,
    string? SiteGroupDisplayName,
    IReadOnlyList<string> EntitlementTypesSupported,
    string GovernanceStatus,
    string ReadinessStatus,
    bool EvidenceCaptureConfigured,
    bool EvidenceCaptureEnabled,
    IReadOnlyList<ManagementPlatformStatutoryEvidenceDocumentProfileDto> RequiredDocumentProfiles,
    IReadOnlyList<string> AllowedMediaTypes,
    long? MaximumUploadSizeBytes,
    int? UploadAuthorizationTtlSeconds,
    string UploadAuthorizationReadiness,
    string UploadFinalizationReadiness,
    string ProtectedStorageProviderClassification,
    string ProtectedStorageReadiness,
    string StoragePrivateAccessPosture,
    string ServerSideEncryptionPosture,
    string ChecksumVerificationReadiness,
    string ProviderMetadataVerificationReadiness,
    string UploadLifecycleReadiness,
    string ValidationLifecycleReadiness,
    string MalwareScanLifecycleReadiness,
    string ReviewabilityLifecycleReadiness,
    string BindingLifecycleReadiness,
    string HoldLifecycleReadiness,
    string DeletionRequestLifecycleReadiness,
    string MalwareScanningExecutionReadiness,
    string SecurePreviewReadiness,
    string RetentionPolicyReadiness,
    string RetentionWorkerReadiness,
    string DeletionWorkerReadiness,
    string ObjectReconciliationReadiness,
    DateTimeOffset LastEvaluatedAt,
    DateTimeOffset? ConfigurationUpdatedAt,
    string FreshnessStatus,
    bool Stale,
    bool Retryable,
    string SupportReference,
    IReadOnlyList<string> Warnings,
    IReadOnlyList<string> Blockers);

public sealed record ManagementPlatformStatutoryEvidenceDocumentProfileDto(
    string ProfileCode,
    string ProfileVersion,
    string RetentionClassCode,
    string RetentionPolicyVersion,
    string RetentionPolicyStatus,
    bool RetentionPolicyApproved);
