import { createOperatorConsoleApiClient, type OperatorConsoleApiClient } from "./apiClient";
import { FormEvent, useMemo, useState } from "react";
import type {
  AccessGateResult,
  DeviceTrustState,
  DeviceTrustStatus,
  OperatorConsoleModule,
  OperatorSessionSummary,
  ShiftAccessState,
  ShiftAccessStatus,
  SessionLookupStatus,
  StatutoryDiscountWorkflowStep,
  StatutoryDiscountReview
} from "./types";

const placeholderSession: OperatorSessionSummary = {
  parkingSessionReference: "Session reference will appear here",
  vehiclePlate: "Plate will appear here",
  entryTime: "Entry time will appear here",
  currentFee: "Current fee will appear here",
  paymentStatus: "Payment status will appear here as read-only context",
  payableBasisStatus: "Backend-approved payable basis will appear here",
  siteDisplayName: "Site / site group will appear here"
};

const placeholderReview: StatutoryDiscountReview = {
  entitlementType: "Senior Citizen",
  validationStatus: "no request",
  operatorInstruction:
    "Evidence capture and backend statutory discount validation will be wired in a later slice."
};

const validationStatuses = [
  "no request",
  "pending operator review",
  "approved",
  "rejected",
  "expired"
];

const statutoryDiscountWorkflowSteps: StatutoryDiscountWorkflowStep[] = [
  {
    title: "Session prerequisite check",
    state: "blocked",
    description: "Requires a resolved active parking session before validation can start."
  },
  {
    title: "Select discount type",
    state: "mock only",
    description: "Senior Citizen and PWD options are visible for workflow shape only."
  },
  {
    title: "Capture structured ID details",
    state: "later slice",
    description: "ID number, name, birth date, and issuing authority fields will be wired later."
  },
  {
    title: "Entitlement fingerprint",
    state: "later slice",
    description: "Duplicate-detection fingerprinting will be generated by backend validation later."
  },
  {
    title: "Optional cropped ID evidence",
    state: "later slice",
    description: "Evidence capture and storage are placeholders only in this frontend slice."
  },
  {
    title: "Operator attestation",
    state: "mock only",
    description: "Operator acknowledgement copy is present, but no attestation is submitted."
  },
  {
    title: "Approve / reject placeholders",
    state: "mock only",
    description: "Decision controls are disabled and do not mutate backend state."
  },
  {
    title: "Backend update",
    state: "later slice",
    description: "Payable-basis update and statutory validation writes will be wired later."
  },
  {
    title: "Audit log",
    state: "later slice",
    description: "Audit event persistence will be added in a later backend-integrated slice."
  }
];

const deviceTrustStatuses: DeviceTrustStatus[] = ["pending", "active", "suspended", "revoked", "lost"];

const shiftAccessStatuses: ShiftAccessStatus[] = ["scheduled", "active", "ended", "suspended"];

const accessGateResults: AccessGateResult[] = [
  "access allowed",
  "device not registered",
  "device suspended/revoked",
  "no active shift",
  "site mismatch"
];

const mockDeviceTrustState: DeviceTrustState = {
  deviceId: "Device ID placeholder",
  deviceName: "Operator kiosk placeholder",
  siteAssignment: "Assigned site placeholder",
  deviceStatus: "pending",
  trustMechanism: "mTLS certificate or browser key binding placeholder"
};

const mockShiftAccessState: ShiftAccessState = {
  operatorRole: "Operator role placeholder",
  assignedSite: "Assigned site placeholder",
  shiftStatus: "scheduled",
  clockIn: "Clock-in placeholder",
  clockOut: "Clock-out placeholder"
};

const operatorConsoleModules: OperatorConsoleModule[] = [
  {
    name: "Session Lookup",
    status: "available",
    description: "Find parking sessions by ticket or plate before reviewing operator workflows."
  },
  {
    name: "Statutory Discount Validation",
    status: "first module",
    description: "Initial module for senior citizen and PWD validation review."
  },
  {
    name: "Registered Device and Shift Access",
    status: "planned",
    description: "Placeholder for device registration and shift-based operator access."
  },
  {
    name: "Supervisor Review and Overrides",
    status: "planned",
    description: "Placeholder for supervised review paths and override workflows."
  },
  {
    name: "Audit and Reporting",
    status: "planned",
    description: "Placeholder for operational audit trails and reporting views."
  }
];

interface AppProps {
  apiClient?: OperatorConsoleApiClient;
}

export function App({ apiClient }: AppProps) {
  const client = useMemo(() => apiClient ?? createOperatorConsoleApiClient(), [apiClient]);
  const [ticketNumber, setTicketNumber] = useState("");
  const [plateNumber, setPlateNumber] = useState("");
  const [lookupStatus, setLookupStatus] = useState<SessionLookupStatus>("not searched");
  const [session, setSession] = useState<OperatorSessionSummary>(placeholderSession);
  const [ambiguousMatches, setAmbiguousMatches] = useState(0);

  const canSearch = ticketNumber.trim().length > 0 || plateNumber.trim().length > 0;

  async function handleSearch(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!canSearch || lookupStatus === "searching") {
      return;
    }

    setLookupStatus("searching");
    setAmbiguousMatches(0);

    const result = await client.findSession({ ticketNumber, plateNumber });

    setLookupStatus(result.status);
    if (result.status === "session found") {
      setSession(result.session);
      return;
    }

    if (result.status === "ambiguous session") {
      setSession(placeholderSession);
      setAmbiguousMatches(result.matches);
      return;
    }

    setSession(placeholderSession);
  }

  const statusCopy = {
    "not searched": "Enter a ticket number or plate number to look up a parking session.",
    searching: "Searching for a matching parking session.",
    "session found": "Session found. Review the read-only session context before statutory discount validation is wired.",
    "not found": "No matching parking session was found for the entered criteria.",
    "ambiguous session": `Multiple matching sessions were found${ambiguousMatches > 0 ? ` (${ambiguousMatches})` : ""}. Operator disambiguation will be wired in a later slice.`
  }[lookupStatus];

  return (
    <main className="appShell" aria-labelledby="app-title">
      <header className="appHeader">
        <div>
          <p className="eyebrow">Operator workspace</p>
          <h1 id="app-title">ExitPass Operator Console</h1>
          <p className="headerCopy">
            Operator-facing console for ExitPass site workflows. Statutory Discount Validation is the first module.
          </p>
        </div>
        <span className="environmentBadge">Scaffold</span>
      </header>

      <section className="platformShell" aria-label="ExitPass Operator Console platform shell">
        <aside className="moduleRail" aria-labelledby="module-navigation-title">
          <div className="panelHeader">
            <p className="eyebrow">Platform modules</p>
            <h2 id="module-navigation-title">Navigation</h2>
          </div>

          <nav aria-label="Operator Console modules">
            {operatorConsoleModules.map((module) => (
              <a className="moduleLink" href={`#${module.name.toLowerCase().replaceAll(" ", "-")}`} key={module.name}>
                <span>{module.name}</span>
                <span className="moduleStatus">{module.status}</span>
              </a>
            ))}
          </nav>

          <p className="moduleRailCopy">
            Payment collection stays outside the Operator Console. Payment status appears only as read-only context.
          </p>
        </aside>

        <section className="workspace" aria-label="Operator Console workspace">
          <section className="moduleOverview" aria-label="Module placeholders">
            {operatorConsoleModules.map((module) => (
              <article className="moduleCard" id={module.name.toLowerCase().replaceAll(" ", "-")} key={module.name}>
                <div>
                  <h3>{module.name}</h3>
                  <p>{module.description}</p>
                </div>
                <span className="moduleStatus">{module.status}</span>
              </article>
            ))}
          </section>

          <section className="panel deviceShiftPanel" aria-labelledby="device-shift-access-title">
            <div className="panelHeader">
              <p className="eyebrow">Read-only placeholder</p>
              <h2 id="device-shift-access-title">Registered Device and Shift Access</h2>
            </div>

            <p className="placeholderCopy">
              Device trust, active shift validation, and site assignment are represented as mock read-only states.
              Backend identity, device, and shift validation will be wired in a later slice.
            </p>

            <div className="accessGrid">
              <section className="accessBlock" aria-labelledby="device-trust-title">
                <div className="accessBlockHeader">
                  <h3 id="device-trust-title">Device trust state</h3>
                  <span className="statusPill">{mockDeviceTrustState.deviceStatus}</span>
                </div>

                <dl className="summaryList">
                  <div>
                    <dt>Device ID</dt>
                    <dd>{mockDeviceTrustState.deviceId}</dd>
                  </div>
                  <div>
                    <dt>Device name</dt>
                    <dd>{mockDeviceTrustState.deviceName}</dd>
                  </div>
                  <div>
                    <dt>Site assignment</dt>
                    <dd>{mockDeviceTrustState.siteAssignment}</dd>
                  </div>
                  <div>
                    <dt>Device status values</dt>
                    <dd>{deviceTrustStatuses.join(", ")}</dd>
                  </div>
                  <div>
                    <dt>Trust mechanism</dt>
                    <dd>{mockDeviceTrustState.trustMechanism}</dd>
                  </div>
                </dl>
              </section>

              <section className="accessBlock" aria-labelledby="shift-state-title">
                <div className="accessBlockHeader">
                  <h3 id="shift-state-title">Shift state</h3>
                  <span className="statusPill">{mockShiftAccessState.shiftStatus}</span>
                </div>

                <dl className="summaryList">
                  <div>
                    <dt>Operator role</dt>
                    <dd>{mockShiftAccessState.operatorRole}</dd>
                  </div>
                  <div>
                    <dt>Assigned site</dt>
                    <dd>{mockShiftAccessState.assignedSite}</dd>
                  </div>
                  <div>
                    <dt>Shift status values</dt>
                    <dd>{shiftAccessStatuses.join(", ")}</dd>
                  </div>
                  <div>
                    <dt>Clock-in</dt>
                    <dd>{mockShiftAccessState.clockIn}</dd>
                  </div>
                  <div>
                    <dt>Clock-out</dt>
                    <dd>{mockShiftAccessState.clockOut}</dd>
                  </div>
                </dl>
              </section>

              <section className="accessBlock" aria-labelledby="access-gate-title">
                <div className="accessBlockHeader">
                  <h3 id="access-gate-title">Access gate result states</h3>
                  <span className="statusPill">mock only</span>
                </div>

                <ul className="stateList">
                  {accessGateResults.map((result) => (
                    <li key={result}>{result}</li>
                  ))}
                </ul>
              </section>
            </div>

            <p className="notice">
              This placeholder does not perform login, device enrollment, certificate handling, browser key
              generation, shift mutation, or backend validation.
            </p>
          </section>

          <section className="layoutGrid" aria-label="Session Lookup and Statutory Discount Validation workspace">
            <form className="panel searchPanel" aria-labelledby="session-search-title" onSubmit={handleSearch}>
              <div className="panelHeader">
                <p className="eyebrow">Session Lookup</p>
                <h2 id="session-search-title">Session search</h2>
              </div>

              <label>
                Ticket number
                <input
                  name="ticketNumber"
                  type="text"
                  placeholder="Enter ticket number"
                  value={ticketNumber}
                  onChange={(event) => setTicketNumber(event.target.value)}
                />
              </label>

              <label>
                Plate number
                <input
                  name="plateNumber"
                  type="text"
                  placeholder="Enter plate number"
                  value={plateNumber}
                  onChange={(event) => setPlateNumber(event.target.value)}
                />
              </label>

              <label>
                Site / site group
                <input value={session.siteDisplayName} readOnly />
              </label>

              <button type="submit" disabled={!canSearch || lookupStatus === "searching"}>
                {lookupStatus === "searching" ? "Searching" : "Search session"}
              </button>

              <div className="lookupState" role="status" aria-live="polite">
                <span className="statusPill">{lookupStatus}</span>
                <p>{statusCopy}</p>
              </div>
            </form>

            <section className="panel" aria-labelledby="session-summary-title">
              <div className="panelHeader">
                <p className="eyebrow">Read-only context</p>
                <h2 id="session-summary-title">Session summary</h2>
              </div>

              <dl className="summaryList">
                <div>
                  <dt>Parking session reference</dt>
                  <dd>{session.parkingSessionReference}</dd>
                </div>
                <div>
                  <dt>Vehicle plate</dt>
                  <dd>{session.vehiclePlate}</dd>
                </div>
                <div>
                  <dt>Entry time</dt>
                  <dd>{session.entryTime}</dd>
                </div>
                <div>
                  <dt>Current fee</dt>
                  <dd>{session.currentFee}</dd>
                </div>
                <div>
                  <dt>Payment status</dt>
                  <dd>{session.paymentStatus}</dd>
                </div>
                <div>
                  <dt>Payable-basis status</dt>
                  <dd>{session.payableBasisStatus}</dd>
                </div>
              </dl>
            </section>

            <section className="panel reviewPanel" aria-labelledby="discount-review-title">
              <div className="panelHeader">
                <p className="eyebrow">First operational module</p>
                <h2 id="discount-review-title">Statutory Discount Validation</h2>
              </div>

              <p className="placeholderCopy">
                This guided workflow can start only after a session is resolved, the session is active, the device
                trust gate is allowed, and the operator has an active shift at the assigned site.
              </p>

              <section className="prerequisiteGrid" aria-label="Statutory discount prerequisite checks">
                <div>
                  <dt>Session prerequisite</dt>
                  <dd>Resolved active session required</dd>
                </div>
                <div>
                  <dt>Device trust gate</dt>
                  <dd>Access allowed required</dd>
                </div>
                <div>
                  <dt>Shift and site gate</dt>
                  <dd>Active shift at assigned site required</dd>
                </div>
                <div>
                  <dt>Payment status</dt>
                  <dd>{session.paymentStatus}</dd>
                </div>
              </section>

              <section className="workflowSteps" aria-label="Statutory discount guided workflow">
                {statutoryDiscountWorkflowSteps.map((step, index) => (
                  <article className="workflowStep" key={step.title}>
                    <div className="stepNumber">{index + 1}</div>
                    <div>
                      <h3>{step.title}</h3>
                      <p>{step.description}</p>
                    </div>
                    <span className="moduleStatus">{step.state}</span>
                  </article>
                ))}
              </section>

              <div className="workflowDetails">
                <section className="accessBlock" aria-labelledby="discount-type-title">
                  <div className="accessBlockHeader">
                    <h3 id="discount-type-title">Select discount type</h3>
                    <span className="statusPill">mock only</span>
                  </div>

                  <div className="reviewControls" aria-label="Discount type">
                    <label>
                      <input type="radio" name="entitlementType" value="Senior Citizen" defaultChecked disabled />
                      Senior Citizen
                    </label>
                    <label>
                      <input type="radio" name="entitlementType" value="PWD" disabled />
                      PWD
                    </label>
                  </div>
                </section>

                <section className="accessBlock" aria-labelledby="id-details-title">
                  <div className="accessBlockHeader">
                    <h3 id="id-details-title">Structured ID details</h3>
                    <span className="statusPill">later slice</span>
                  </div>

                  <dl className="summaryList">
                    <div>
                      <dt>ID number</dt>
                      <dd>ID number placeholder</dd>
                    </div>
                    <div>
                      <dt>Cardholder name</dt>
                      <dd>Cardholder name placeholder</dd>
                    </div>
                    <div>
                      <dt>Issuing authority</dt>
                      <dd>Issuing authority placeholder</dd>
                    </div>
                  </dl>
                </section>

                <section className="accessBlock" aria-labelledby="evidence-title">
                  <div className="accessBlockHeader">
                    <h3 id="evidence-title">Evidence and fingerprint</h3>
                    <span className="statusPill">later slice</span>
                  </div>

                  <dl className="summaryList">
                    <div>
                      <dt>Entitlement fingerprint</dt>
                      <dd>Fingerprint placeholder</dd>
                    </div>
                    <div>
                      <dt>Optional cropped ID evidence</dt>
                      <dd>Cropped ID evidence placeholder</dd>
                    </div>
                    <div>
                      <dt>Operator attestation</dt>
                      <dd>Attestation placeholder only; no operator statement is submitted.</dd>
                    </div>
                  </dl>
                </section>
              </div>

              <section className="accessBlock" aria-labelledby="validation-outcome-title">
                <div className="accessBlockHeader">
                  <h3 id="validation-outcome-title">Validation outcome placeholders</h3>
                  <span className="statusPill">{placeholderReview.validationStatus}</span>
                </div>

                <dl className="summaryList">
                  <div>
                    <dt>Available statuses</dt>
                    <dd>{validationStatuses.join(", ")}</dd>
                  </div>
                  <div>
                    <dt>Operator instruction</dt>
                    <dd>{placeholderReview.operatorInstruction}</dd>
                  </div>
                  <div>
                    <dt>Backend update</dt>
                    <dd>Backend update placeholder for statutory validation and payable-basis update.</dd>
                  </div>
                  <div>
                    <dt>Audit log</dt>
                    <dd>Audit log placeholder for operator decision traceability.</dd>
                  </div>
                </dl>
              </section>

              <p className="notice">
                Backend statutory discount validation, evidence storage, entitlement fingerprinting, payable-basis
                update, and audit logging will be wired in later slices. Payment collection is out of scope. Payment
                status is displayed read-only when needed for operator context.
              </p>

              <div className="actionBar" aria-label="Operator decision controls">
                <button type="button" disabled>
                  Approve
                </button>
                <button type="button" disabled>
                  Reject
                </button>
                <button type="button" disabled>
                  Request more information
                </button>
              </div>
            </section>
          </section>
        </section>
      </section>
    </main>
  );
}
