export const operatorFiscalReportingRoute="/operator-console/fiscal-reporting";
export const fiscalReportingPermissions={ejRead:"fiscal-reporting.ej.read",ejExport:"fiscal-reporting.ej.export",xRead:"fiscal-reporting.x.read",xGenerate:"fiscal-reporting.x.generate",zRead:"fiscal-reporting.z.read",zGenerate:"fiscal-reporting.z.generate"} as const;
export interface FiscalPeriod{fiscalReportingPeriodId:string;businessDayDate:string;periodStartAt:string;periodEndAt:string;currencyCode:string;periodSequence:number;status:string;expectedZStateVersion:number}
export interface Amounts{grossSalesAmountMinorUnits:number;netSalesAmountMinorUnits:number;vatableSalesAmountMinorUnits:number;vatAmountMinorUnits:number;vatExemptSalesAmountMinorUnits:number;zeroRatedSalesAmountMinorUnits:number;discountAmountMinorUnits:number;voidAmountMinorUnits:number;adjustmentAmountMinorUnits:number}
export interface Tender{classification:string;transactionCount:number;amountMinorUnits:number;currencyCode:string} export interface Discount{classification:string;qualifyingDocumentCount:number;discountAmountMinorUnits:number;vatExemptionAmountMinorUnits:number;currencyCode:string}
export interface Reading{reportReference:string;reportKind:"X_READING"|"Z_READING";fiscalReportingPeriodId:string;businessDayDate:string;periodStartAt:string;periodEndAt:string;generatedAt:string;transactionCount:number;amounts:Amounts;currencyCode:string;periodSequence:number;reportStatus:string;tenders:Tender[];discounts:Discount[]}
export interface History{currentPeriod?:FiscalPeriod;readings:Reading[]}
export interface EjInvoice{fiscalDocumentId:string;fiscalDocumentNumber:string;businessDayDate:string;issuedAt:string;printableText:string}
export interface OperatorFiscalReportingClient{readEj(site:string,start:string,end:string,search?:string):Promise<EjInvoice[]>;ejUrl(site:string,start:string,end:string,search?:string):string;readX(site:string):Promise<History>;generateX(site:string):Promise<void>;readZ(site:string):Promise<History>;generateZ(site:string):Promise<void>;readingUrl(site:string,kind:"x"|"z",reference:string):string}

export function createOperatorFiscalReportingClient(fetchImpl:typeof fetch=fetch,csrfToken?:()=>string|null):OperatorFiscalReportingClient{
 const root="/v1/ops/operator-console/fiscal-reporting/sites";const p=(s:string,x:string)=>`${root}/${encodeURIComponent(s)}${x}`;
 async function json(path:string,init?:RequestInit){const r=await fetchImpl(path,{credentials:"same-origin",cache:"no-store",...init,headers:{Accept:"application/json","Content-Type":"application/json","X-Correlation-Id":crypto.randomUUID(),...init?.headers}});const v=await r.json();if(!r.ok)throw new Error(rec(v).message as string||"Fiscal reporting failed safely.");return rec(v);}
 const mutation=(body:unknown):RequestInit=>{const token=csrfToken?.();if(!token)throw new Error("A current anti-forgery token is required for fiscal report generation.");return{method:"POST",headers:{"X-CSRF-Token":token},body:JSON.stringify(body)}};
 return{async readEj(s,a,b,q){const x=new URLSearchParams({periodStart:a,periodEnd:b});if(q?.trim())x.set("search",q.trim());const v=await json(p(s,`/electronic-journal?${x}`));if(!Array.isArray(v.invoices))throw bad();return v.invoices.map(i=>{const o=rec(i);return{fiscalDocumentId:str(o.fiscalDocumentId),fiscalDocumentNumber:str(o.fiscalDocumentNumber),businessDayDate:str(o.businessDayDate),issuedAt:str(o.issuedAt),printableText:str(o.printableText)}});},ejUrl(s,a,b,q){const x=new URLSearchParams({periodStart:a,periodEnd:b});if(q?.trim())x.set("search",q.trim());return p(s,`/electronic-journal/download?${x}`);},async readX(s){return hist(await json(p(s,"/x-readings")),"X_READING");},async generateX(s){await json(p(s,"/x-readings"),mutation({operationKey:crypto.randomUUID()}));},async readZ(s){return hist(await json(p(s,"/z-readings")),"Z_READING");},async generateZ(s){await json(p(s,"/z-readings"),mutation({operationKey:crypto.randomUUID(),confirmClose:true}));},readingUrl(s,k,r){return p(s,`/${k}-readings/${encodeURIComponent(r)}/download`);}};
}
export function createOperatorFiscalReportingFixture():OperatorFiscalReportingClient{const period:FiscalPeriod={fiscalReportingPeriodId:"91000000-0000-4000-8000-000000000001",businessDayDate:"2026-09-10",periodStartAt:"2026-09-09T16:00:00Z",periodEndAt:"2026-09-10T16:00:00Z",currencyCode:"PHP",periodSequence:91,status:"OPEN",expectedZStateVersion:14};const amounts:Amounts={grossSalesAmountMinorUnits:11200,netSalesAmountMinorUnits:11200,vatableSalesAmountMinorUnits:10000,vatAmountMinorUnits:1200,vatExemptSalesAmountMinorUnits:0,zeroRatedSalesAmountMinorUnits:0,discountAmountMinorUnits:0,voidAmountMinorUnits:0,adjustmentAmountMinorUnits:0};const r=(k:"X_READING"|"Z_READING"):Reading=>({reportReference:`${k[0]}-20260910-001`,reportKind:k,fiscalReportingPeriodId:period.fiscalReportingPeriodId,businessDayDate:period.businessDayDate,periodStartAt:period.periodStartAt,periodEndAt:period.periodEndAt,generatedAt:"2026-09-10T08:15:00Z",transactionCount:1,amounts,currencyCode:"PHP",periodSequence:91,reportStatus:"COMMITTED",tenders:[{classification:"cash",transactionCount:1,amountMinorUnits:11200,currencyCode:"PHP"}],discounts:[]});const ej:EjInvoice={fiscalDocumentId:"92000000-0000-4000-8000-000000000001",fiscalDocumentNumber:"SI-00000001",businessDayDate:"2026-09-10",issuedAt:"2026-09-10T01:00:00Z",printableText:"SALES INVOICE\r\nSI No.             : SI-00000001\r\nCustomer Name      : Juan Dela Cruz\r\nAddress            : 123 Sample Street\r\nTIN                : 123-456-789-000\r\nBusiness Style     : Retail\r\nOSCA ID No.        : OSCA-0001\r\nCustomer Signature : ____________________\r\nVATable Sales      : PHP 100.00\r\nVAT Amount         : PHP 12.00\r\nVAT Exempt Sales   : PHP 0.00\r\nZero Rated Sales   : PHP 0.00\r\n"};return{readEj:async()=>[ej],ejUrl:(s)=>`/v1/ops/operator-console/fiscal-reporting/sites/${s}/electronic-journal/download`,readX:async()=>({currentPeriod:period,readings:[r("X_READING")]}),generateX:async()=>{},readZ:async()=>({currentPeriod:period,readings:[r("Z_READING")]}),generateZ:async()=>{},readingUrl:(s,k,x)=>`/v1/ops/operator-console/fiscal-reporting/sites/${s}/${k}-readings/${x}/download`};}
function hist(v:Record<string,unknown>,kind:Reading["reportKind"]):History{if(!Array.isArray(v.readings))throw bad();return{currentPeriod:v.currentPeriod?per(rec(v.currentPeriod)):undefined,readings:v.readings.map(x=>read(rec(x),kind))};}function per(o:Record<string,unknown>):FiscalPeriod{return{fiscalReportingPeriodId:str(o.fiscalReportingPeriodId),businessDayDate:str(o.businessDayDate),periodStartAt:str(o.periodStartAt),periodEndAt:str(o.periodEndAt),currencyCode:str(o.currencyCode),periodSequence:num(o.periodSequence),status:str(o.status),expectedZStateVersion:num(o.expectedZStateVersion)}}function read(o:Record<string,unknown>,k:Reading["reportKind"]):Reading{if(o.reportKind!==k||!Array.isArray(o.tenders)||!Array.isArray(o.discounts))throw bad();const a=rec(o.amounts);return{reportReference:str(o.reportReference),reportKind:k,fiscalReportingPeriodId:str(o.fiscalReportingPeriodId),businessDayDate:str(o.businessDayDate),periodStartAt:str(o.periodStartAt),periodEndAt:str(o.periodEndAt),generatedAt:str(o.generatedAt),transactionCount:num(o.transactionCount),amounts:{grossSalesAmountMinorUnits:num(a.grossSalesAmountMinorUnits),netSalesAmountMinorUnits:num(a.netSalesAmountMinorUnits),vatableSalesAmountMinorUnits:num(a.vatableSalesAmountMinorUnits),vatAmountMinorUnits:num(a.vatAmountMinorUnits),vatExemptSalesAmountMinorUnits:num(a.vatExemptSalesAmountMinorUnits),zeroRatedSalesAmountMinorUnits:num(a.zeroRatedSalesAmountMinorUnits),discountAmountMinorUnits:num(a.discountAmountMinorUnits),voidAmountMinorUnits:num(a.voidAmountMinorUnits),adjustmentAmountMinorUnits:num(a.adjustmentAmountMinorUnits)},currencyCode:str(o.currencyCode),periodSequence:num(o.periodSequence),reportStatus:str(o.reportStatus),tenders:o.tenders.map(v=>{const t=rec(v);return{classification:str(t.classification),transactionCount:num(t.transactionCount),amountMinorUnits:num(t.amountMinorUnits),currencyCode:str(t.currencyCode)}}),discounts:o.discounts.map(v=>{const d=rec(v);return{classification:str(d.classification),qualifyingDocumentCount:num(d.qualifyingDocumentCount),discountAmountMinorUnits:num(d.discountAmountMinorUnits),vatExemptionAmountMinorUnits:num(d.vatExemptionAmountMinorUnits),currencyCode:str(d.currencyCode)}})}}function rec(v:unknown):Record<string,unknown>{if(typeof v!=="object"||v===null||Array.isArray(v))throw bad();return v as Record<string,unknown>}function str(v:unknown){if(typeof v!=="string"||!v)throw bad();return v}function num(v:unknown){if(typeof v!=="number"||!Number.isSafeInteger(v))throw bad();return v}function bad(){return new Error("The authoritative fiscal reporting response was malformed.")}
