import { useEffect, useMemo, useState } from "react";
import type { ManagementPlatformReportScope, ManagementPlatformSite } from "./types";
import { fiscalReportingPermissions, type ElectronicJournalResult, type FiscalReading, type FiscalReadingHistory, type FiscalReportingClient } from "./fiscalReporting";

export function FiscalReportingPage({client,sites,scopes,permissions}:{client:FiscalReportingClient;sites:readonly ManagementPlatformSite[];scopes:readonly ManagementPlatformReportScope[];permissions:readonly string[]}){
  const [scope,setScope]=useState(scopes[0]?.scopeReference??sites[0]?.siteId??"");
  const scopedSites=useMemo(()=>scopes.find(x=>x.scopeReference===scope)?.scopeType==="SITE_GROUP"?sites:sites.filter(x=>x.siteId===scope),[scope,scopes,sites]);
  const [siteId,setSiteId]=useState(scopedSites[0]?.siteId??sites[0]?.siteId??"");
  const [tab,setTab]=useState<"ej"|"x"|"z">("ej");
  const [start,setStart]=useState("2026-09-10T00:00:00Z"); const [end,setEnd]=useState("2026-09-11T00:00:00Z"); const [search,setSearch]=useState("");
  const [ej,setEj]=useState<ElectronicJournalResult>(); const [x,setX]=useState<FiscalReadingHistory>(); const [z,setZ]=useState<FiscalReadingHistory>();
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string>(); const [confirming,setConfirming]=useState(false);
  const has=(p:string)=>permissions.includes(p);
  useEffect(()=>{const next=scopedSites[0]?.siteId;if(next&&!scopedSites.some(s=>s.siteId===siteId))setSiteId(next);},[scope]);
  async function load(){if(!siteId)return;setBusy(true);setError(undefined);try{const tasks:Promise<void>[]=[];if(has(fiscalReportingPermissions.ejRead))tasks.push(client.readElectronicJournal(siteId,start,end,search).then(setEj));if(has(fiscalReportingPermissions.xRead))tasks.push(client.readXHistory(siteId).then(setX));if(has(fiscalReportingPermissions.zRead))tasks.push(client.readZHistory(siteId).then(setZ));await Promise.all(tasks);}catch(e){setError(e instanceof Error?e.message:"Fiscal reporting is unavailable.");}finally{setBusy(false);}}
  useEffect(()=>{void load();},[siteId]);
  async function generate(kind:"x"|"z"){setBusy(true);setError(undefined);try{await(kind==="x"?client.generateX(siteId):client.generateZ(siteId));if(kind==="x")setX(await client.readXHistory(siteId));else{setZ(await client.readZHistory(siteId));setConfirming(false);}}catch(e){setError(e instanceof Error?e.message:"Generation failed safely.");}finally{setBusy(false);}}
  if(!sites.length)return <section className="stateMessage warning"><h2>No authorized fiscal Site</h2><p>No Site is available for these fiscal reporting permissions.</p></section>;
  return <section className="panel fiscalReporting" aria-labelledby="fiscal-reporting-title">
    <div className="pageTitle"><div><p className="eyebrow">POS-authoritative reports</p><h2 id="fiscal-reporting-title">Fiscal Reporting</h2><p>Electronic Journal, X Reading, and Z Reading are retrieved from the bound Site POS Server through Central PMS.</p></div><span className="statusPill">Governed access</span></div>
    <div className="reportFilters"><label>Portfolio scope<select value={scope} onChange={e=>setScope(e.target.value)}>{(scopes.length?scopes:sites.map(s=>({scopeType:"SITE" as const,scopeReference:s.siteId,displayName:s.displayName}))).map(s=><option key={s.scopeReference} value={s.scopeReference}>{s.scopeType==="SITE_GROUP"?"Site Group: ":"Site: "}{s.displayName}</option>)}</select></label><label>Authoritative Site<select value={siteId} onChange={e=>setSiteId(e.target.value)}>{scopedSites.map(s=><option key={s.siteId} value={s.siteId}>{s.displayName}</option>)}</select></label></div>
    <div className="reportTabs" role="tablist" aria-label="Fiscal report type"><button type="button" role="tab" aria-selected={tab==="ej"} onClick={()=>setTab("ej")}>Electronic Journal</button><button type="button" role="tab" aria-selected={tab==="x"} onClick={()=>setTab("x")}>X Reading</button><button type="button" role="tab" aria-selected={tab==="z"} onClick={()=>setTab("z")}>Z Reading</button></div>
    {busy&&<p role="status">Loading authoritative POS reporting data…</p>}{error&&<div className="stateMessage danger" role="alert"><h3>Fiscal reporting unavailable</h3><p>{error}</p></div>}
    {tab==="ej"&&<EjPanel result={ej} start={start} end={end} search={search} setStart={setStart} setEnd={setEnd} setSearch={setSearch} onLoad={load} download={has(fiscalReportingPermissions.ejExport)&&ej?.invoices.length?client.electronicJournalDownloadUrl(siteId,start,end,search):undefined} canRead={has(fiscalReportingPermissions.ejRead)}/>}
    {tab==="x"&&<ReadingPanel kind="X" history={x} canRead={has(fiscalReportingPermissions.xRead)} canGenerate={has(fiscalReportingPermissions.xGenerate)} onGenerate={()=>generate("x")} download={r=>client.readingDownloadUrl(siteId,"x",r)}/>}
    {tab==="z"&&<><ReadingPanel kind="Z" history={z} canRead={has(fiscalReportingPermissions.zRead)} canGenerate={false} download={r=>client.readingDownloadUrl(siteId,"z",r)}/>{has(fiscalReportingPermissions.zGenerate)&&(!confirming?<button className="dangerButton" type="button" onClick={()=>setConfirming(true)}>Generate Z Reading</button>:<div className="zConfirmation" role="alertdialog" aria-label="Confirm Z Reading close"><h3>Close the current fiscal reporting period?</h3><p>Generating Z Reading closes and finalizes the current reporting period according to authoritative POS behavior. This cannot be performed by the browser or undone here.</p><button className="dangerButton" type="button" onClick={()=>generate("z")} disabled={busy}>Confirm close and generate Z</button><button type="button" onClick={()=>setConfirming(false)}>Cancel</button></div>)}</>}
  </section>;
}

function EjPanel({result,start,end,search,setStart,setEnd,setSearch,onLoad,download,canRead}:{result?:ElectronicJournalResult;start:string;end:string;search:string;setStart:(v:string)=>void;setEnd:(v:string)=>void;setSearch:(v:string)=>void;onLoad:()=>void;download?:string;canRead:boolean}){
 if(!canRead)return <p className="stateMessage warning">Electronic Journal permission is required.</p>;
 return <div className="fiscalPane" role="tabpanel"><h3>Electronic Journal</h3><p>Exact visible Sales Invoice text supplied by POS authority. The browser does not create or reconstruct the journal artifact.</p><div className="reportFilters"><label>Period start (UTC)<input aria-label="EJ period start UTC" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Period end (UTC)<input aria-label="EJ period end UTC" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>SI / transaction reference<input aria-label="Search Electronic Journal" value={search} onChange={e=>setSearch(e.target.value)}/></label><button type="button" onClick={onLoad}>View journal</button>{download&&<a className="primaryButton" href={download}>Download authoritative .txt</a>}</div>{result&&result.invoices.length===0&&<p role="status">No Sales Invoice activity exists for this period.</p>}{result?.invoices.map(invoice=><article className="invoiceText" key={invoice.fiscalDocumentId}><header><strong>{invoice.fiscalDocumentNumber}</strong><span>{new Date(invoice.issuedAt).toLocaleString()}</span></header><pre>{invoice.printableText}</pre></article>)}</div>;
}
function ReadingPanel({kind,history,canRead,canGenerate,onGenerate,download}:{kind:"X"|"Z";history?:FiscalReadingHistory;canRead:boolean;canGenerate:boolean;onGenerate?:()=>void;download:(r:string)=>string}){
 if(!canRead)return <p className="stateMessage warning">{kind} Reading permission is required.</p>;return <div className="fiscalPane" role="tabpanel"><div className="readingTitle"><div><h3>{kind} Reading</h3><p>{kind==="X"?"Non-closing observation of the current reporting period.":"Closing fiscal report history."}</p></div>{canGenerate&&<button type="button" onClick={onGenerate}>Generate {kind} Reading</button>}</div>{history?.currentPeriod?<dl className="periodCard"><div><dt>Current business date</dt><dd>{history.currentPeriod.businessDayDate}</dd></div><div><dt>Reporting period</dt><dd>{history.currentPeriod.periodStartAt} — {history.currentPeriod.periodEndAt}</dd></div><div><dt>Status</dt><dd>{history.currentPeriod.status}</dd></div></dl>:<p role="status">No open fiscal reporting period is available.</p>}<div className="tableViewport"><table><thead><tr><th>Reference</th><th>Generated</th><th>Transactions</th><th>Gross sales</th><th>VATable</th><th>VAT</th><th>VAT exempt</th><th>Zero rated</th><th>Discounts</th><th>Voids</th><th>Adjustments</th><th>Net sales</th><th>Tenders</th><th>Output</th></tr></thead><tbody>{history?.readings.map(r=><tr key={r.reportReference}><td>{r.reportReference}</td><td>{new Date(r.generatedAt).toLocaleString()}</td><td>{r.transactionCount}</td><td>{money(r.amounts.grossSalesAmountMinorUnits,r.currencyCode)}</td><td>{money(r.amounts.vatableSalesAmountMinorUnits,r.currencyCode)}</td><td>{money(r.amounts.vatAmountMinorUnits,r.currencyCode)}</td><td>{money(r.amounts.vatExemptSalesAmountMinorUnits,r.currencyCode)}</td><td>{money(r.amounts.zeroRatedSalesAmountMinorUnits,r.currencyCode)}</td><td>{money(r.amounts.discountAmountMinorUnits,r.currencyCode)}</td><td>{money(r.amounts.voidAmountMinorUnits,r.currencyCode)}</td><td>{money(r.amounts.adjustmentAmountMinorUnits,r.currencyCode)}</td><td>{money(r.amounts.netSalesAmountMinorUnits,r.currencyCode)}</td><td>{r.tenders.length?r.tenders.map(t=>`${t.classification}: ${money(t.amountMinorUnits,t.currencyCode)}`).join("; "):"None"}</td><td><a href={download(r.reportReference)}>Print / download</a></td></tr>)}</tbody></table></div></div>;
}
function money(v:number,c:string){return new Intl.NumberFormat("en-PH",{style:"currency",currency:c}).format(v/100);}
